#!/bin/sh
# tmux가 항상 최신 forwarded agent를 쓰도록 고정 경로 링크 갱신
if [ -S "$SSH_AUTH_SOCK" ]; then
    ln -sf "$SSH_AUTH_SOCK" ~/.ssh/ssh_auth_sock
fi

# ~/.ssh/rc가 있으면 sshd가 xauth를 대신 처리하지 않으므로 직접 처리 (sshd(8) 예시)
if read proto cookie && [ -n "$DISPLAY" ]; then
    if [ "$(echo "$DISPLAY" | cut -c1-10)" = 'localhost:' ]; then
        echo add unix:$(echo "$DISPLAY" | cut -c11-) "$proto" "$cookie"
    else
        echo add "$DISPLAY" "$proto" "$cookie"
    fi | xauth -q -
fi
